# Generated by Django 5.1.4 on 2025-03-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_serversubscription_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serversubscription',
            name='key',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
