# Generated by Django 5.1.4 on 2025-03-16 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('dashboard', '0019_alter_serversubscription_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversubscription',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.payment'),
        ),
    ]
