# Generated by Django 5.1.6 on 2025-05-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=255)),
                ('models', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
