# Generated by Django 5.1.6 on 2025-05-13 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appreloader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='models',
        ),
    ]
