"""
Django settings for AtomicShield project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Config directory
CONFIG_DIR = os.path.join(BASE_DIR.parent, "config")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "mr9y5jf)fp5^==jhccttp!d!9&hh@57@dbb+0-idp!-d!i0%r+"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Bin directory
if DEBUG:
    BIN_DIR = os.path.join(BASE_DIR.parent, "bin", "debug")
else:
    BIN_DIR = os.path.join(BASE_DIR.parent, "bin", "production")

ALLOWED_HOSTS = [
    "atomic-shield.com",
    "www.atomic-shield.com",
    "127.0.0.1",
    "157.173.212.241",
]

CSRF_TRUSTED_ORIGINS = [
    "https://atomic-shield.com",
    "https://www.atomic-shield.com",
]

# Application definition

INSTALLED_APPS = [
    "channels",
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "django_recaptcha",
    "home",
    "authentication",
    "dashboard",
    "anticheat",
    "resources",
]


SITE_ID = 1

ASGI_APPLICATION = "AtomicShield.asgi.application"

MIDDLEWARE = [
    "django_browser_reload.middleware.BrowserReloadMiddleware",  # Debug
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if DEBUG:
    INSTALLED_APPS.append("django_browser_reload")
    # INSTALLED_APPS.append("debug_toolbar")

    # MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware")

    INTERNAL_IPS = [
        "127.0.0.1",
    ]

ROOT_URLCONF = "AtomicShield.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "dashboard.context_preprocessor.preprocess_sidebar_context",
            ],
        },
    },
]

WSGI_APPLICATION = "AtomicShield.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "atomicshield",
        "USER": "root",
        "PASSWORD": "",
        "HOST": "localhost",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Media Configurations
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {message}",
            "style": "{",
        },
        "uvicorn": {
            "format": "[{asctime}] {levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "rich.logging.RichHandler",
            "rich_tracebacks": True,
            "show_time": True,
        },
        "alltypes": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "../logs/console.log"),
            "formatter": "verbose",
        }
    },
    "root": {
        "handlers": ["alltypes", "console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "alltypes"],
            "level": "INFO",
            "propagate": False,
        },
        "uvicorn": {
            "handlers": ["console", "alltypes"],
            "level": "INFO",
            "propagate": False,  # Avoid duplicate logs
        },
        "uvicorn.error": {
            "handlers": ["console", "alltypes"],
            "level": "ERROR",
            "propagate": False,
        },
        "uvicorn.access": {
            "handlers": ["console", "alltypes"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Project names
ANTICHEAT_NAME = "AtomicShield"
ANTICHEAT_VERSION = "1.0b"
ANTICHEAT_NAME_LONG = f"{ANTICHEAT_NAME} {ANTICHEAT_VERSION}"

# Discord settings
DISCORD_INVITE = "https://discord.gg/YFCRffsZKK"
BOT_AVATAR_URL = "https://cdn.discordapp.com/icons/1164637086637371505/020e433238f8e8302c51276a0327b09d.png?size=1024"
if DEBUG:
    DETECTIONS_WEBHOOK_URL = "https://discord.com/api/webhooks/1300813067138891828/N09MygqqoFn2FlSFH1ipxe1-c-oEboMUfM8UKIMHAJzWnNcHP-EmyCiQeEZPrBjOM86o"
else:
    DETECTIONS_WEBHOOK_URL = "https://discord.com/api/webhooks/1300813067138891828/N09MygqqoFn2FlSFH1ipxe1-c-oEboMUfM8UKIMHAJzWnNcHP-EmyCiQeEZPrBjOM86o"

UNFOLD = {
    "SITE_HEADER": f"{ANTICHEAT_NAME} STAFF",
    "SITE_SYMBOL": "shield",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
    },
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "1 126 134",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
    },
    # Other configurations...
}

# Authentication Settings
LOGIN_URL = "/auth/signin"
LOGIN_REDIRECT_URL = "/dashboard/main/"
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24 * 1  # 1 Day

# Sessions
SESSION_COOKIE_AGE = (60 * 60 * 24) / 2  # 12h

# Captcha Settings
if DEBUG:
    RECAPTCHA_PUBLIC_KEY = "6Ld5FS8qAAAAADYrdex9VsqXwRmEcbDonIBywDOZ"
    RECAPTCHA_PRIVATE_KEY = "6Ld5FS8qAAAAAGq5JUx7rsAAL2rFOPHeV9WAwYA4"
else:
    RECAPTCHA_PUBLIC_KEY = ""
    RECAPTCHA_PRIVATE_KEY = ""
RECAPTCHA_REQUIRED_SCORE = 0.9


# Admin Settings
ADMINS = [("Hyper", "hosniadem400@gmail.com")]

# Mail Settings
DEFAULT_FROM_EMAIL = "AtomicShield@localhost"
EMAIL_SUBJECT_PREFIX = "[AtomicShield] "

if not DEBUG:
    # Redirect from http to httpsS
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    
    USE_X_FORWARDED_HOST = True

    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_SECONDS = 31536000  # Enforce HTTPS for 1 year

    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = None
    SESSION_COOKIE_HTTPONLY = True

    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_USE_SESSIONS = True
