"""
Django settings for AtomicShield project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
from datetime import timedelta
from django.templatetags.static import static
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Config directory
CONFIG_DIR = os.path.join(BASE_DIR.parent, "config")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "mr9y5jf)fp5^==jhccttp!d!9&hh@57@dbb+0-idp!-d!i0%r+"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Bin directory
if DEBUG:
    BIN_DIR = os.path.join(BASE_DIR.parent, "bin", "debug")
else:
    BIN_DIR = os.path.join(BASE_DIR.parent, "bin", "production")

ALLOWED_HOSTS = [
    "*",
    ".atomic-shield.com",
    "atomic-shield.com",
]

CSRF_TRUSTED_ORIGINS = (
    [
        "https://atomic-shield.com",
        "https://www.atomic-shield.com",
        "http://31.97.180.157:8000",
    ]
    if not DEBUG
    else ["http://31.97.180.157:553"]
)

CORS_ALLOWED_ORIGINS = CSRF_TRUSTED_ORIGINS
CORS_ALLOW_ALL_ORIGINS = True
# Application definition

INSTALLED_APPS = [
    # "daphne",
    "channels",
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "django_recaptcha",
    "django_hosts",
    "unfold.contrib.forms",
    "unfold.contrib.simple_history",
    "simple_history",
    "api",
    "home",
    "authentication",
    "dashboard",
    "anticheat",
    "resources",
    "appreloader",
    "rest_framework",
    "rest_framework.authtoken",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    # "allauth",
    # "allauth.account",
    # "allauth.socialaccount",
    # "allauth.socialaccount.providers.discord",
    "rest_framework_simplejwt",
    "corsheaders",
]

SITE_ID = 1
ASGI_APPLICATION = "AtomicShield.asgi.application"

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    # "allauth.account.middleware.AccountMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django_hosts.middleware.HostsRequestMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",  # Debug
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "AtomicShield.middleware.ExceptionHandlerMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django_hosts.middleware.HostsResponseMiddleware",
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

if DEBUG:
    INSTALLED_APPS.append("django_browser_reload")
    # INSTALLED_APPS.append("debug_toolbar")

    # MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware")

    INTERNAL_IPS = [
        "127.0.0.1",
    ]

ROOT_URLCONF = "AtomicShield.urls"

# Domain Settings
ROOT_HOSTCONF = "AtomicShield.hosts"
DEFAULT_HOST = "www"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "dashboard.context_preprocessor.preprocess_sidebar_context",
            ],
        },
    },
]

WSGI_APPLICATION = "AtomicShield.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "atomicshield",
        "USER": "root",
        "PASSWORD": "",
        "HOST": "localhost",
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Cache settings
REDIS_URL = "redis://127.0.0.1:6379/1"
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

CHANNEL_LAYERS = {
        "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
    ),
}
REST_USE_JWT = False


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media Configurations
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

import os

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        # Console: only show INFO+ (no debug)
        "console": {
            "class": "rich.logging.RichHandler",
            "rich_tracebacks": True,
            "show_time": True,
            "show_path": False,
            "level": "DEBUG",
        },
        "alltypes": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "../logs/console.log"),
            "formatter": "verbose",
        },
        "error_file": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "../logs/error.log"),
            "formatter": "verbose",
        },
        # Debug-only goes to file
        "debug_file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "../logs/debug.log"),
            "formatter": "verbose",
        },
    },
    "root": {
        # removed "console" here so DEBUG doesn’t hit stdout
        "handlers": ["console", "alltypes", "error_file", "debug_file"],
        "level": "DEBUG",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "alltypes", "error_file"],  # console still here, but INFO+ only
            "level": "INFO",
            "propagate": False,
        },
        "uvicorn": {
            "handlers": ["console", "alltypes", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        "channels": {
            # If you don’t want DEBUG spam in terminal, drop console here too
            "handlers": ["alltypes", "error_file", "debug_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "hypercorn": {
            # If you don’t want DEBUG spam in terminal, drop console here too
            "handlers": ["console", "alltypes", "error_file", "debug_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "autobahn": {
            "handlers": ["console", "alltypes", "error_file", "debug_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "twisted": {
            "handlers": ["console", "alltypes", "error_file", "debug_file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}


# Project names
ANTICHEAT_NAME = "AtomicShield"
ANTICHEAT_VERSION = "1.0b"
ANTICHEAT_NAME_LONG = f"{ANTICHEAT_NAME} {ANTICHEAT_VERSION}"

# Discord settings
DISCORD_INVITE = "https://discord.gg/YFCRffsZKK"
BOT_AVATAR_URL = "https://atomic-shield.com/static/assets/images/logo.png"
if DEBUG:
    DETECTIONS_WEBHOOK_URL = "https://discord.com/api/webhooks/1300813067138891828/N09MygqqoFn2FlSFH1ipxe1-c-oEboMUfM8UKIMHAJzWnNcHP-EmyCiQeEZPrBjOM86o"
else:
    DETECTIONS_WEBHOOK_URL = "https://discord.com/api/webhooks/1300813067138891828/N09MygqqoFn2FlSFH1ipxe1-c-oEboMUfM8UKIMHAJzWnNcHP-EmyCiQeEZPrBjOM86o"

UNFOLD = {
    "SITE_TITLE": f"{ANTICHEAT_NAME} STAFF",
    "SITE_HEADER": f"{ANTICHEAT_NAME} STAFF",
    "SITE_SUBHEADER": _(f"{ANTICHEAT_NAME} AntiCheat"),
    "SITE_SYMBOL": "shield",
    "SITE_ICON": {
        "light": lambda request: static("/image/logo-ico.svg"),
        "dark": lambda request: static("/image/logo-ico.svg"),
    },
    "SHOW_BACK_BUTTON": True,
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
    },
    "DASHBOARD_CALLBACK": "dashboard.views.dashboard_callback",
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/svg+xml",
            "href": lambda request: static("/image/logo-ico.svg"),
        },
    ],
    "COLORS": {
        "base": {
            "50": "249 250 251",
            "100": "243 244 246",
            "200": "229 231 235",
            "300": "209 213 219",
            "400": "156 163 175",
            "500": "107 114 128",
            "600": "75 85 99",
            "700": "55 65 81",
            "800": "31 41 55",
            "900": "17 24 39",
            "950": "3 7 18",
        },
        "primary": {
            "50": "236 250 255",
            "100": "207 243 255",
            "200": "179 235 255",
            "300": "136 224 255",
            "400": "82 208 255",
            "500": "41 186 252",
            "600": "0 165 245",
            "700": "0 140 220",
            "800": "0 115 190",
            "900": "0 92 160",
            "950": "0 72 128",
        },
    },
}

# Authentication Settings
LOGIN_URL = "/auth/signin"
LOGIN_REDIRECT_URL = "/dashboard/main/"
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24 * 1  # 1 Day

# Sessions
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_COOKIE_AGE = (60 * 60 * 24) / 2  # 12h
SESSION_CACHE_ALIAS = "default"

# Captcha Settings
RECAPTCHA_PUBLIC_KEY = "6Lee-LoqAAAAAO4gH6AC1DR0R-6V6lPpFzf2nYlx"
RECAPTCHA_PRIVATE_KEY = "6Lee-LoqAAAAAIPaRqeCahr1sC8ABgaKeRU1tsE9"
RECAPTCHA_REQUIRED_SCORE = 0.6

DISCORD_CLIENT_ID="1404072529684861058"
DISCORD_CLIENT_SECRET="N43jrx37HOUzTyXxY5ZP0N-SzdlMh4_e"
DISCORD_REDIRECT_URI="http://atomic-shield.com/api/auth/discord/callback"

GOOGLE_CLIENT_ID = "1091637385561-5l7jpbubori3m6jekd6nn1bu7g999p3f.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
GOOGLE_REDIRECT_URI = "https://atomic-shield.com/api/auth/google/callback"

SOCIALACCOUNT_PROVIDERS = {
    "discord": {
        "APP": {
            "client_id": "YOUR_DISCORD_CLIENT_ID",
            "secret": "YOUR_DISCORD_CLIENT_SECRET",
            "key": "",
        },
        "SCOPE": [
            "identify",
            "email",
        ],
    }
}

# Admin Settings
ADMINS = [("Hyper", "hosniadem400@gmail.com")]
APPEND_SLASH = True

# Mail Settings
DEFAULT_FROM_EMAIL = "AtomicShield@localhost"
EMAIL_SUBJECT_PREFIX = "[AtomicShield] "

# Tebex Configurations
TEBEX_SECRET_KEY = "433788188a0ba1d3bb38b21fc39b2967"

if not DEBUG:
    # Redirect from http to https
    # SECURE_SSL_REDIRECT = False
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True

    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_SECONDS = 31536000  # Enforce HTTPS for 1 year

    SESSION_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_HTTPONLY = True

    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = False
    CSRF_COOKIE_HTTPONLY = False
    CSRF_USE_SESSIONS = False
