# Generated by Django 5.0.7 on 2024-09-29 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anticheat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('ip', models.CharField(blank=True, max_length=49)),
                ('serial', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='EagleAntiCheat Development Team', max_length=32)),
                ('title', models.CharField(max_length=50, null=True)),
                ('announcement', models.TextField(max_length=4096)),
                ('mention_everyone', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('seens', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'announcements',
                'db_table': 'announcements',
            },
        ),
        migrations.CreateModel(
            name='PatchNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='EagleAntiCheat Development Team', max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('patchnotes', models.TextField()),
                ('mention_everyone', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('seens', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'patch-notes',
                'db_table': 'patchnotes',
            },
        ),
        migrations.CreateModel(
            name='ServerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('expires_at', models.IntegerField()),
                ('type', models.IntegerField(choices=[(1, 'MTA:SA')], null=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'subscriptions',
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='GameServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=49)),
                ('port', models.IntegerField()),
                ('key', models.CharField(default='UNREGISTRED', max_length=16, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'MTA:SA')], null=True)),
                ('status', models.IntegerField(choices=[(1, 'UnSubscribed'), (2, 'Online'), (3, 'Offline')], default=1)),
                ('configurations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anticheat.anticheatconfigurations')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subscriptions', models.ManyToManyField(related_name='game_servers', to='dashboard.serversubscription')),
                ('whitelists', models.ManyToManyField(related_name='servers', to='dashboard.whitelist')),
            ],
            options={
                'verbose_name_plural': 'gameservers',
                'db_table': 'gameservers',
            },
        ),
    ]
