# Generated by Django 5.0.7 on 2024-07-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='EagleAntiCheat Development Team', max_length=32)),
                ('title', models.CharField(max_length=50, null=True)),
                ('announcement', models.TextField(max_length=4096)),
                ('mention_everyone', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'announcements',
                'db_table': 'announcements',
            },
        ),
        migrations.CreateModel(
            name='GameServers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=49)),
                ('port', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('subscriptions', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'gameservers',
                'db_table': 'gameservers',
            },
        ),
        migrations.CreateModel(
            name='PatchNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='EagleAntiCheat Development Team', max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('patchnotes', models.TextField()),
                ('mention_everyone', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'patch-notes',
                'db_table': 'patchnotes',
            },
        ),
    ]
