# Generated by Django 5.0.7 on 2024-09-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitelist',
            options={'verbose_name': 'Whitelist', 'verbose_name_plural': 'Whitelists'},
        ),
        migrations.AlterModelTable(
            name='whitelist',
            table='whitelists',
        ),
    ]
