# Generated by Django 5.0.7 on 2024-09-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_whitelist_options_alter_whitelist_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serversubscription',
            name='expires_at',
            field=models.DurationField(),
        ),
    ]
