# Generated by Django 5.0.7 on 2024-10-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_serversubscription_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameserver',
            name='name',
            field=models.CharField(default='Game Server', max_length=32),
            preserve_default=False,
        ),
    ]
