# Generated by Django 5.0.7 on 2024-10-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_gameserver_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whitelist',
            old_name='username',
            new_name='name',
        ),
    ]
