# Generated by Django 5.0.7 on 2024-10-06 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_username_whitelist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameserver',
            name='whitelists',
        ),
        migrations.AddField(
            model_name='whitelist',
            name='game_server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.gameserver'),
            preserve_default=False,
        ),
    ]
