# Generated by Django 5.0.7 on 2024-10-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_gameserver_whitelists_whitelist_game_server'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcements',
            options={'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='gameserver',
            options={'verbose_name': 'Game Server', 'verbose_name_plural': 'Game Servers'},
        ),
        migrations.AlterModelOptions(
            name='patchnotes',
            options={'verbose_name': 'Patchnote'},
        ),
        migrations.AlterField(
            model_name='whitelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whitelist',
            name='last_update_at',
            field=models.DateTimeField(auto_now=True, default=0),
            preserve_default=False,
        ),
    ]
