# Generated by Django 5.0.7 on 2024-10-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0007_alter_announcements_options_alter_gameserver_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default="7"
        ),
        migrations.AlterField(
            model_name='whitelist',
            name='last_update_at',
            field=models.DateTimeField(auto_now=True),
            preserve_default="7"
        ),
    ]
