# Generated by Django 5.0.7 on 2024-11-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_announcements_options_alter_gameserver_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='author',
            field=models.CharField(default='AtomicShield Development Team', max_length=32),
        ),
        migrations.AlterField(
            model_name='patchnotes',
            name='author',
            field=models.CharField(default='AtomicShield Development Team', max_length=32),
        ),
    ]
