# Generated by Django 5.0.7 on 2025-01-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_announcements_author_alter_patchnotes_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='type',
            field=models.IntegerField(choices=[(2, 'FiveM'), (1, 'Multi Theft Auto: San Andreas (MTA:SA)')], null=True),
        ),
        migrations.AlterField(
            model_name='serversubscription',
            name='type',
            field=models.IntegerField(choices=[(2, 'FiveM'), (1, 'Multi Theft Auto: San Andreas (MTA:SA)')], null=True),
        ),
    ]
