# Generated by Django 5.0.7 on 2025-01-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_gameserver_type_alter_serversubscription_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Whitelist',
        ),
    ]
