# Generated by Django 5.0.7 on 2025-01-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_delete_whitelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='type',
            field=models.IntegerField(choices=[(2, 'FiveM')], null=True),
        ),
        migrations.AlterField(
            model_name='serversubscription',
            name='type',
            field=models.IntegerField(choices=[(2, 'FiveM')], null=True),
        ),
    ]
