# Generated by Django 5.1.4 on 2025-03-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_gameserver_type_alter_serversubscription_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serversubscription',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='serversubscription',
            name='plan',
            field=models.IntegerField(choices=[(1, 'Basic'), (2, 'Pro'), (3, 'Entreprise')], default=1),
            preserve_default=False,
        ),
    ]
