# Generated by Django 5.1.4 on 2025-03-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_serversubscription_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serversubscription',
            name='name',
        ),
    ]
