# Generated by Django 5.1.4 on 2025-03-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_serversubscription_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='key',
            field=models.CharField(default='UNREGISTRED', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='serversubscription',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='serversubscription',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0),
        ),
    ]
