# Generated by Django 5.1.4 on 2025-03-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_gameserver_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serversubscription',
            name='plan',
            field=models.IntegerField(choices=[(1, 'Basic'), (2, 'Pro'), (3, 'Entreprise'), (4, 'Free')]),
        ),
    ]
