# Generated by Django 5.1.4 on 2025-03-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_serversubscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversubscription',
            name='key',
            field=models.CharField(max_length=20, blank=True),
            preserve_default=False,
        ),
    ]
