# Generated by Django 5.1.4 on 2025-03-16 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('dashboard', '0020_serversubscription_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serversubscription',
            name='payment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.payment'),
        ),
    ]
