# Generated by Django 5.1.4 on 2025-03-16 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_serversubscription_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameserver',
            name='key',
        ),
    ]
