# Generated by Django 5.1.7 on 2025-03-19 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0031_alter_detectionreport_detection_type'),
        ('dashboard', '0022_remove_gameserver_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='configurations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_server', to='anticheat.anticheatconfigurations'),
        ),
    ]
