# Generated by Django 5.1.7 on 2025-03-19 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0032_alter_ban_report'),
        ('dashboard', '0023_alter_gameserver_configurations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameserver',
            name='configurations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_servers', to='anticheat.anticheatconfigurations'),
        ),
        migrations.AlterField(
            model_name='serversubscription',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
