# Generated by Django 5.1.7 on 2025-03-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_gameserver_configurations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameserver',
            options={'verbose_name': 'Server', 'verbose_name_plural': 'Servers'},
        ),
        migrations.AlterField(
            model_name='announcements',
            name='announcement',
            field=models.TextField(),
        ),
    ]
