# Generated by Django 5.1.7 on 2025-03-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_gameserver_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
