# Generated by Django 5.2 on 2025-05-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_announcements_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serversubscription',
            name='plan',
            field=models.IntegerField(choices=[(1, 'Basic'), (2, 'Pro'), (3, 'Entreprise'), (4, 'Free'), (5, 'Lifetime')]),
        ),
    ]
