# Generated by Django 5.2.5 on 2025-08-10 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_serversubscription_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameServerModerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_dashboard', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=False)),
                ('can_kick_players', models.BooleanField(default=False)),
                ('can_ban_players', models.BooleanField(default=False)),
                ('can_view_anticheat_logs', models.BooleanField(default=False)),
                ('can_manage_configuration', models.BooleanField(default=False)),
                ('can_manage_webhook_settings', models.BooleanField(default=False)),
                ('can_access_interactive_map', models.BooleanField(default=False)),
                ('can_access_multi_stream', models.BooleanField(default=False)),
                ('can_manage_moderators', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
