# Generated by Django 5.2.5 on 2025-08-10 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_gameservermoderator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameservermoderator',
            options={'verbose_name': 'Game Server Moderator', 'verbose_name_plural': 'Game Server Moderators'},
        ),
        migrations.AddField(
            model_name='gameservermoderator',
            name='game_server',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderators', to='dashboard.gameserver'),
            preserve_default=False,
        ),
    ]
