# Generated by Django 5.2.5 on 2025-08-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_gameservermoderator_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameservermoderator',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
