# Generated by Django 5.2.5 on 2025-08-10 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_gameservermoderator_added_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorInviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.JSONField(default=[])),
                ('invited_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('game_server', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invite_tokens', to='dashboard.gameserver')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to='dashboard.gameservermoderator')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Server Invite Token',
                'verbose_name_plural': 'Game Server Invite Tokens',
            },
        ),
    ]
