# Generated by Django 5.2.5 on 2025-08-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_moderatorinvitetoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderatorinvitetoken',
            name='game_server',
        ),
        migrations.AddField(
            model_name='moderatorinvitetoken',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moderatorinvitetoken',
            name='sent_to_email',
            field=models.BooleanField(default=False),
        ),
    ]
