# Generated by Django 5.2.5 on 2025-08-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_remove_moderatorinvitetoken_game_server_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatorinvitetoken',
            name='permissions',
            field=models.JSONField(default=list),
        ),
    ]
