# Generated by Django 5.2.5 on 2025-08-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_moderatorinvitetoken_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatorinvitetoken',
            name='token',
            field=models.CharField(db_index=True, default='', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
