# Generated by Django 5.2.5 on 2025-08-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_moderatorinvitetoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatorinvitetoken',
            name='token',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
