# Generated by Django 5.2.5 on 2025-08-13 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_moderatorinvitetoken_game_server_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderatorinvitetoken',
            name='accepted',
        ),
        migrations.AlterField(
            model_name='moderatorinvitetoken',
            name='game_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invite_tokens', to='dashboard.gameserver'),
        ),
        migrations.AlterField(
            model_name='moderatorinvitetoken',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderatorinvitetoken',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invite_tokens_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
