# Generated by Django 5.2.5 on 2025-08-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_remove_moderatorinvitetoken_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatorinvitetoken',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'accepted'), (-1, 'Declined')], default=0),
        ),
    ]
