# Generated by Django 5.1.3 on 2025-08-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_moderatorinvitetoken_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatorinvitetoken',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'accepted'), (-1, 'declined')], default=0),
        ),
    ]
