# Generated by Django 5.1.3 on 2025-08-13 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_alter_moderatorinvitetoken_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='category',
            field=models.CharField(default='announcement', max_length=32),
        ),
        migrations.AddField(
            model_name='announcements',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcements',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcements',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcements',
            name='read_time',
            field=models.CharField(default='2 min read', max_length=32),
        ),
        migrations.AddField(
            model_name='announcements',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='authored_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='seens',
            field=models.ManyToManyField(blank=True, related_name='seen_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
