# Generated by Django 5.2.5 on 2025-08-13 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_alter_moderatorinvitetoken_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='seens',
            field=models.ManyToManyField(blank=True, related_name='seen_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
