# Generated by Django 5.1.3 on 2025-08-13 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_announcements_category_announcements_comments_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='author_name',
            field=models.CharField(default='AtomicShield Development Team', max_length=32),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='author',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='authored_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
