# Generated by Django 5.2.5 on 2025-08-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_alter_announcements_seens'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='category',
            field=models.CharField(default='announcement', max_length=32),
        ),
        migrations.AddField(
            model_name='announcements',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcements',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcements',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcements',
            name='read_time',
            field=models.CharField(default='2 min read', max_length=32),
        ),
        migrations.AddField(
            model_name='announcements',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
