# Generated by Django 5.1.3 on 2025-08-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_alter_announcements_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patchnotes',
            options={'ordering': ['-date'], 'verbose_name': 'Patchnote'},
        ),
        migrations.RemoveField(
            model_name='patchnotes',
            name='patchnotes',
        ),
        migrations.RemoveField(
            model_name='patchnotes',
            name='title',
        ),
        migrations.AddField(
            model_name='patchnotes',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patchnotes',
            name='highlights',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='patchnotes',
            name='release_type',
            field=models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('patch', 'Patch')], default='stable', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patchnotes',
            name='status_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patchnotes',
            name='version',
            field=models.CharField(default='stable', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patchnotes',
            name='author',
            field=models.CharField(default='AtomicShield Team', max_length=64),
        ),
    ]
