# Generated by Django 5.2.5 on 2025-08-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_alter_announcements_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='read_time',
        ),
        migrations.RemoveField(
            model_name='announcements',
            name='views',
        ),
    ]
