# Generated by Django 5.2.5 on 2025-08-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_remove_announcements_comments_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderatorinvitetoken',
            name='sent_to_email',
        ),
    ]
