# Generated by Django 5.1.3 on 2025-08-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_alter_patchnotes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchnotes',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
