# Generated by Django 5.2.5 on 2025-08-13 15:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0045_remove_moderatorinvitetoken_sent_to_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.SmallIntegerField(choices=[(10, 'Player Banned'), (11, 'Player Kicked'), (12, 'Player Unbanned'), (13, 'Warning Issued'), (20, 'Config Changed'), (30, 'Admin Login')], db_index=True)),
                ('severity', models.SmallIntegerField(choices=[(10, 'Low'), (20, 'Medium'), (30, 'High'), (40, 'Critical')], db_index=True)),
                ('actor_object_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('summary', models.CharField(blank=True, max_length=140)),
                ('details', models.TextField(blank=True)),
                ('server_instance', models.CharField(blank=True, db_index=True, max_length=128)),
                ('target_object_id', models.CharField(blank=True, max_length=128, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('source', models.CharField(db_index=True, default='system', max_length=32)),
                ('reviewed', models.BooleanField(db_index=True, default=False)),
                ('actor_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_audit_entries', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='dashboard_a_timesta_998fee_idx'), models.Index(fields=['action', 'timestamp'], name='dashboard_a_action_4bac99_idx'), models.Index(fields=['severity', 'timestamp'], name='dashboard_a_severit_bb171b_idx'), models.Index(fields=['server_instance', 'timestamp'], name='dashboard_a_server__570ba7_idx'), models.Index(fields=['actor_object_id'], name='dashboard_a_actor_o_cb63f1_idx')],
            },
        ),
    ]
