# Generated by Django 5.1.3 on 2025-08-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_patchnotes_title'),
    ]

    operations = [
    ]
