# Generated by Django 5.2.5 on 2025-08-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_auditlogentry'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlogentry',
            name='dashboard_a_server__570ba7_idx',
        ),
        migrations.RemoveField(
            model_name='auditlogentry',
            name='server_instance',
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='action',
            field=models.SmallIntegerField(choices=[(1, 'Player Banned'), (2, 'Player Kicked'), (3, 'Player Unbanned'), (4, 'Warning Issued'), (5, 'Config Changed'), (6, 'Admin Login')], db_index=True),
        ),
    ]
