# Generated by Django 5.1.3 on 2025-08-13 15:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_auto_20250813_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patchnotes',
            options={'ordering': ['-date'], 'verbose_name': 'Patchnote', 'verbose_name_plural': 'Patchnotes'},
        ),
        migrations.RemoveField(
            model_name='patchnotes',
            name='title',
        ),
        migrations.AlterField(
            model_name='patchnotes',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
