# Generated by Django 5.1.3 on 2025-08-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_alter_patchnotes_options_remove_patchnotes_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchnotes',
            name='title',
            field=models.CharField(default='', max_length=128),
        ),
    ]
