# Generated by Django 5.2.5 on 2025-08-13 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0047_remove_auditlogentry_dashboard_a_server__570ba7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogentry',
            name='game_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audit_logs', to='dashboard.gameserver'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['game_server', 'timestamp'], name='dashboard_a_game_se_398782_idx'),
        ),
    ]
