# Generated by Django 5.2.5 on 2025-08-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0048_auditlogentry_game_server_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogentry',
            name='category',
            field=models.IntegerField(choices=[(1, 'Player'), (2, 'Server'), (3, 'Security'), (4, 'System'), (5, 'Moderation')], db_index=True, default=4),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['category', 'timestamp'], name='dashboard_a_categor_01eff2_idx'),
        ),
    ]
