# Generated by Django 5.1.3 on 2025-08-13 16:09

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_patchnotes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchnotes',
            name='title',
            field=models.JSONField(blank=True, default=list, validators=[dashboard.models.validate_max_4]),
        ),
    ]
