# Generated by Django 5.1.3 on 2025-08-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_alter_patchnotes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchnotes',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
