# Generated by Django 5.2.5 on 2025-08-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_auditlogentry_category_and_more'),
        ('dashboard', '0051_alter_patchnotes_title'),
    ]

    operations = [
    ]
