# Generated by Django 5.1.3 on 2025-08-13 21:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_merge_20250813_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file_size_mb', models.DecimalField(decimal_places=2, max_digits=6)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('format', models.CharField(blank=True, max_length=20)),
                ('stability', models.CharField(choices=[('stable', 'Stable'), ('beta', 'Beta')], default='stable', max_length=16)),
                ('recommended', models.BooleanField(default=False)),
                ('changelog', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Download', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='releases/')),
                ('external_url', models.URLField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='dashboard.release')),
            ],
        ),
    ]
