# Generated by Django 5.2.5 on 2025-08-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_release_releaseasset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-release_date'], 'verbose_name': 'Release', 'verbose_name_plural': 'Releases'},
        ),
        migrations.RemoveField(
            model_name='release',
            name='file_size_mb',
        ),
        migrations.AlterField(
            model_name='release',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
