# Generated by Django 5.2.5 on 2025-08-15 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_alter_auditlogentry_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='game_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='dashboard.gameserver'),
        ),
    ]
