# Generated by Django 5.2.5 on 2025-08-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_alter_auditlogentry_game_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='action',
            field=models.SmallIntegerField(choices=[(1, 'Player Banned'), (2, 'Player Kicked'), (3, 'Player Unbanned'), (4, 'Warning Issued'), (5, 'Configuration Changed'), (6, 'Admin Login'), (7, 'Server Created'), (8, 'Moderator Invite Request'), (9, 'Moderator Suspend'), (10, 'Moderator Reactivate'), (11, 'Moderator Remove'), (12, 'Moderator Update'), (13, 'Moderator Invite Reject'), (14, 'Moderator Invite Accept'), (15, 'False Positive Report'), (16, 'Server Start'), (17, 'Player Request Join'), (18, 'AntiCheat Shutdown'), (19, 'Player Quit'), (20, 'Cheat Detected')], db_index=True),
        ),
    ]
