# Generated by Django 5.2.5 on 2025-08-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_alter_auditlogentry_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameservermoderator',
            name='can_screenshot_players',
            field=models.BooleanField(default=False),
        ),
    ]
