# Generated by Django 5.1.4 on 2025-03-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tebex_payment_id', models.CharField(db_index=True, default='<Unknown>', max_length=128, unique=True)),
                ('transaction_id', models.CharField(max_length=512, unique=True)),
                ('customer_id', models.CharField(default='<Unknown>', max_length=64)),
                ('customer_firstname', models.CharField(default='<Unknown>', max_length=64)),
                ('customer_lastname', models.CharField(default='<Unknown>', max_length=64)),
                ('customer_username', models.CharField(default='<Unknown>', max_length=64)),
                ('customer_email', models.TextField(default='<Unknown>')),
                ('customer_country', models.CharField(default='<Unknown>', max_length=16)),
                ('customer_postalcode', models.CharField(default='<Unknown>', max_length=16)),
                ('customer_ip', models.CharField(default='<Unknown>', max_length=49)),
                ('tebex_date', models.CharField(max_length=32)),
                ('status', models.IntegerField(choices=[(1, 'Completed'), (2, 'Refund'), (3, 'Chargeback'), (4, 'Declined'), (5, 'Pending Checkout'), (6, 'Refund Pending')], null=True)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=16)),
                ('payment_method', models.CharField(max_length=64)),
                ('payment_refundable', models.BooleanField(null=True)),
                ('tax', models.IntegerField()),
                ('tax_currency', models.CharField(max_length=16)),
                ('gateway_tax', models.IntegerField()),
                ('creator_code', models.CharField(max_length=256, null=True)),
                ('coupons', models.JSONField(default=list)),
                ('recurring_payment_refrence', models.TextField(null=True)),
                ('paid_products', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
            },
        ),
    ]
