# Generated by Django 5.0.7 on 2024-09-29 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntiCheatConfigurationCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'AntiCheat Config Category',
                'verbose_name_plural': 'AntiCheat Config Categories',
                'db_table': 'anticheat_configuration_categories',
            },
        ),
        migrations.CreateModel(
            name='AntiCheatConfigurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'AntiCheat Configuration',
                'verbose_name_plural': 'AntiCheat Configurations',
                'db_table': 'anticheat_configurations',
            },
        ),
        migrations.CreateModel(
            name='ClientHWID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('mta_serial', models.CharField(blank=True, max_length=32)),
                ('disks', models.JSONField(default=list)),
                ('cpuid', models.CharField(max_length=64)),
                ('motherboard_serial', models.CharField(max_length=64)),
                ('bios_version', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Client HWID',
                'verbose_name_plural': 'Client HWIDS',
                'db_table': 'client_hwids',
            },
        ),
        migrations.CreateModel(
            name='MaliciousSignatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('signatures', models.JSONField(default=list)),
                ('type', models.IntegerField(choices=[(1, 'MTA:SA')], default=1)),
                ('priority', models.IntegerField(default=None, null=True)),
                ('ban_message', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Malicious Signature',
                'verbose_name_plural': 'Malicious Signatures',
                'db_table': 'malicious_signatures',
            },
        ),
        migrations.CreateModel(
            name='AntiCheatConfigTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('server_type', models.IntegerField(choices=[(1, 'MTA:SA')], default=1)),
                ('config_type', models.IntegerField(choices=[(1, 'Boolean'), (2, 'String'), (3, 'Integer')], default=1)),
                ('default_value', models.CharField(blank=True, max_length=50)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anticheat.anticheatconfigurationcategories')),
            ],
            options={
                'verbose_name': 'AntiCheat Config Template',
                'verbose_name_plural': 'AntiCheat Config Templates',
                'db_table': 'anticheat_config_templates',
            },
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.PositiveIntegerField(null=True)),
                ('reason', models.CharField(max_length=96, null=True)),
                ('hwid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anticheat.clienthwid')),
            ],
            options={
                'verbose_name': 'Ban',
                'verbose_name_plural': 'Bans',
                'db_table': 'bans',
            },
        ),
    ]
