# Generated by Django 5.0.7 on 2024-09-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='ends_at',
            field=models.DurationField(db_comment='Ban Duration', null=True),
        ),
    ]
