# Generated by Django 5.0.7 on 2024-09-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0002_alter_ban_ends_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='ends_at',
            field=models.DurationField(null=True),
        ),
    ]
