# Generated by Django 5.0.7 on 2024-10-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0005_malicioussignatures_ban_duaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticheatconfigtemplates',
            name='pseudo_name',
            field=models.CharField(default='whitelist', max_length=16),
            preserve_default=False,
        ),
    ]
