# Generated by Django 5.0.7 on 2024-10-05 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0006_anticheatconfigtemplates_pseudo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticheatconfigurationcategories',
            name='server_type',
            field=models.IntegerField(choices=[(1, 'MTA:SA')], default=1),
        ),
        migrations.AlterField(
            model_name='anticheatconfigtemplates',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='anticheat.anticheatconfigurationcategories'),
        ),
    ]
