# Generated by Django 5.0.7 on 2024-10-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0007_anticheatconfigurationcategories_server_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticheatconfigtemplates',
            name='pseudo_name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
