# Generated by Django 5.0.7 on 2024-10-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0008_alter_anticheatconfigtemplates_pseudo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticheatconfigtemplates',
            name='pseudo_name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
