# Generated by Django 5.0.7 on 2024-10-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0009_alter_anticheatconfigtemplates_pseudo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticheatconfigtemplates',
            name='default_value',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
