# Generated by Django 5.0.7 on 2024-10-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0010_alter_anticheatconfigtemplates_default_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienthwid',
            name='computer_name',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
