# Generated by Django 5.0.7 on 2024-10-26 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0011_clienthwid_computer_name'),
        ('dashboard', '0007_alter_announcements_options_alter_gameserver_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='game_server',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.gameserver'),
            preserve_default=False,
        ),
    ]
