# Generated by Django 5.0.7 on 2024-10-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0012_ban_game_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
