# Generated by Django 5.0.7 on 2024-11-01 09:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0014_alter_ban_game_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warns', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
                ('hwid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anticheat.clienthwid')),
            ],
            options={
                'verbose_name': 'Warning',
                'verbose_name_plural': 'Warnings',
                'db_table': 'warnings',
            },
        ),
    ]
