# Generated by Django 5.0.7 on 2024-11-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0015_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienthwid',
            name='pnp_device',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
