# Generated by Django 5.0.7 on 2025-01-04 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0018_alter_clienthwid_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticheatconfigtemplates',
            name='server_type',
            field=models.IntegerField(choices=[(2, 'FiveM'), (1, 'Multi Theft Auto: San Andreas (MTA:SA)')], default=1),
        ),
        migrations.AlterField(
            model_name='anticheatconfigurationcategories',
            name='server_type',
            field=models.IntegerField(choices=[(2, 'FiveM'), (1, 'Multi Theft Auto: San Andreas (MTA:SA)')], default=1),
        ),
        migrations.AlterField(
            model_name='malicioussignatures',
            name='type',
            field=models.IntegerField(choices=[(2, 'FiveM'), (1, 'Multi Theft Auto: San Andreas (MTA:SA)')], default=1),
        ),
        migrations.CreateModel(
            name='DetectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.JSONField(default=dict)),
                ('screenshot', models.ImageField(upload_to='media/detections/proofs')),
                ('hwid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anticheat.clienthwid')),
            ],
        ),
    ]
