# Generated by Django 5.0.7 on 2025-01-05 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0020_alter_detectionreport_options_ban_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anticheat.detectionreport'),
        ),
    ]
