# Generated by Django 5.0.7 on 2025-01-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0021_alter_ban_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ban',
            name='report',
        ),
    ]
