# Generated by Django 5.0.7 on 2025-01-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0022_remove_ban_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectionreport',
            options={},
        ),
        migrations.AlterModelTable(
            name='detectionreport',
            table=None,
        ),
    ]
