# Generated by Django 5.0.7 on 2025-01-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0023_alter_detectionreport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectionreport',
            options={'verbose_name': 'Detection Report', 'verbose_name_plural': 'Detection Reports'},
        ),
        migrations.AlterModelTable(
            name='detectionreport',
            table='detection_reports',
        ),
    ]
