# Generated by Django 5.0.7 on 2025-01-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0027_alter_ban_game_server_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienthwid',
            name='mta_serial',
        ),
    ]
