# Generated by Django 5.0.7 on 2025-01-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0028_remove_clienthwid_mta_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticheatconfigtemplates',
            name='server_type',
            field=models.IntegerField(choices=[(2, 'FiveM')], default=2),
        ),
        migrations.AlterField(
            model_name='anticheatconfigurationcategories',
            name='server_type',
            field=models.IntegerField(choices=[(2, 'FiveM')], default=2),
        ),
        migrations.AlterField(
            model_name='ban',
            name='reason',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='detectionreport',
            name='detection_type',
            field=models.IntegerField(choices=[(0, 'Custom'), (1, 'Unauthorized Thread'), (2, 'Unrecognized IAT'), (3, 'Direct X DLL Found'), (4, 'Secure Boot Disabled'), (5, 'Debug Mode Enabled'), (6, 'Test Signing Enabled'), (7, 'Inject Dll'), (8, 'Cheat Signature Found'), (9, 'Malicious Process opened FiveM handle'), (10, 'Malicious Driver Found'), (11, 'Thread Shell Code')]),
        ),
        migrations.AlterField(
            model_name='malicioussignatures',
            name='type',
            field=models.IntegerField(choices=[(2, 'FiveM')], default=2),
        ),
    ]
