# Generated by Django 5.1.4 on 2025-03-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0029_alter_anticheatconfigtemplates_server_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienthwid',
            name='discord_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='clienthwid',
            name='fivem_license',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='clienthwid',
            name='fivem_token',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='clienthwid',
            name='steam',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
