# Generated by Django 5.1.7 on 2025-03-19 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0031_alter_detectionreport_detection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='anticheat.detectionreport'),
        ),
    ]
