# Generated by Django 5.1.7 on 2025-03-23 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0032_alter_ban_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anticheatconfigtemplates',
            options={'verbose_name': 'Configuration', 'verbose_name_plural': 'Configurations'},
        ),
        migrations.AlterModelOptions(
            name='anticheatconfigurationcategories',
            options={'verbose_name': 'Configuration Category', 'verbose_name_plural': 'Configuration Categories'},
        ),
        migrations.AlterModelOptions(
            name='anticheatconfigurations',
            options={'verbose_name': 'Server Configuration', 'verbose_name_plural': 'Server Configurations'},
        ),
        migrations.AlterModelOptions(
            name='clienthwid',
            options={'verbose_name': 'HWID', 'verbose_name_plural': 'HWIDs'},
        ),
    ]
