# Generated by Django 5.1.7 on 2025-03-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0033_alter_anticheatconfigtemplates_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiCheatVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.IntegerField()),
                ('minor', models.IntegerField(default=0)),
                ('patch', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(0, 'Stable'), (2, 'Beta'), (3, 'Deprecated')])),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
                'db_table': 'versions',
            },
        ),
        migrations.AlterModelOptions(
            name='malicioussignatures',
            options={'verbose_name': 'Signature', 'verbose_name_plural': 'Signatures'},
        ),
    ]
