# Generated by Django 5.1.7 on 2025-03-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0034_anticheatversion_alter_malicioussignatures_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticheatversion',
            name='is_current_version',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anticheatversion',
            name='type',
            field=models.IntegerField(choices=[(3, 'Deprecated'), (2, 'Beta'), (0, 'Stable')]),
        ),
    ]
