# Generated by Django 5.1.7 on 2025-04-01 08:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0036_anticheatversion_entity_historicalclienthwid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalClientHWID',
            new_name='hwids_logs',
        ),
    ]
