# Generated by Django 5.2 on 2025-05-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0037_rename_historicalclienthwid_hwids_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistedProcesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('type', models.IntegerField(choices=[(2, 'FiveM')], default=2)),
            ],
            options={
                'verbose_name': 'Whitelisted Process',
                'verbose_name_plural': 'Whitelisted Processes',
                'db_table': 'whitelisted_processes',
            },
        ),
    ]
