# Generated by Django 5.2 on 2025-05-09 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0038_whitelistedprocesses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhitelistedProcesses',
            new_name='WhitelistedProcess',
        ),
    ]
