# Generated by Django 5.2 on 2025-05-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0039_rename_whitelistedprocesses_whitelistedprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='threat_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=256, null=True)),
                ('found_path', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Threat File',
                'verbose_name_plural': 'Threat Files',
                'db_table': 'threat_files',
            },
        ),
    ]
