# Generated by Django 5.2 on 2025-05-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0040_threatfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatfile',
            name='hash',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='threatfile',
            name='found_path',
            field=models.CharField(default='unknown', max_length=256),
            preserve_default=False,
        ),
    ]
