# Generated by Django 5.2 on 2025-05-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0041_threatfile_hash_alter_threatfile_found_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatfile',
            name='uploaded_by',
            field=models.ForeignKey(default=154, on_delete=django.db.models.deletion.CASCADE, to='anticheat.clienthwid'),
            preserve_default=False,
        ),
    ]
