# Generated by Django 5.2 on 2025-05-30 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0042_threatfile_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_code', models.CharField(max_length=32)),
                ('exception_address', models.CharField(max_length=32)),
                ('registers', models.JSONField()),
                ('crash_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anticheat.clienthwid')),
            ],
            options={
                'verbose_name': 'Crash Report',
            },
        ),
    ]
