# Generated by Django 5.2 on 2025-05-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0043_crashreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crashreport',
            name='exception_address',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='crashreport',
            name='exception_code',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='crashreport',
            name='registers',
            field=models.JSONField(default=dict),
        ),
    ]
