# Generated by Django 5.2 on 2025-05-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0044_alter_crashreport_exception_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crashreport',
            name='error',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
