# Generated by Django 5.2 on 2025-05-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0045_crashreport_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='crashreport',
            name='exception_flags',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crashreport',
            name='exception_address',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crashreport',
            name='exception_code',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
