# Generated by Django 5.2 on 2025-05-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0046_crashreport_exception_flags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crashreport',
            name='module_base',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
