# Generated by Django 5.2 on 2025-05-31 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0047_crashreport_module_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='crashreport',
            name='crashed_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 31, 20, 13, 20, 635240, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
