# Generated by Django 5.2.3 on 2025-06-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0048_crashreport_crashed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malicioussignatures',
            name='signatures',
            field=models.TextField(),
        ),
    ]
