# Generated by Django 5.2.3 on 2025-06-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0049_alter_malicioussignatures_signatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malicioussignatures',
            name='signatures',
            field=models.JSONField(default=list),
        ),
    ]
