# Generated by Django 5.2.3 on 2025-07-16 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0050_alter_malicioussignatures_signatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='hwid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='anticheat.clienthwid'),
        ),
        migrations.AlterField(
            model_name='detectionreport',
            name='hwid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anticheat.clienthwid'),
        ),
    ]
