# Generated by Django 5.1.6 on 2025-08-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0051_alter_ban_hwid_alter_detectionreport_hwid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anticheatconfigurations',
            table=None,
        ),
        migrations.AlterModelTable(
            name='clienthwid',
            table=None,
        ),
        migrations.AlterModelTable(
            name='detectionreport',
            table=None,
        ),
        migrations.AlterModelTable(
            name='malicioussignatures',
            table=None,
        ),
    ]
