# Generated by Django 5.1.6 on 2025-08-06 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0052_alter_anticheatconfigurations_table_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientHWID',
            new_name='HWID',
        ),
    ]
