# Generated by Django 5.1.6 on 2025-08-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0053_rename_clienthwid_hwid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anticheatversion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ban',
            table=None,
        ),
        migrations.AlterModelTable(
            name='threatfile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='warning',
            table=None,
        ),
        migrations.AlterModelTable(
            name='whitelistedprocess',
            table=None,
        ),
    ]
