# Generated by Django 5.2.5 on 2025-08-09 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0054_alter_anticheatversion_table_alter_ban_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiCheatConfigSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Configuration Section',
                'verbose_name_plural': 'Configuration Sections',
            },
        ),
        migrations.CreateModel(
            name='AntiCheatConfigurationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('icon', models.CharField(max_length=32)),
                ('server_type', models.IntegerField(choices=[(2, 'FiveM')], default=2)),
            ],
            options={
                'verbose_name': 'Configuration Category',
                'verbose_name_plural': 'Configuration Categories',
            },
        ),
        migrations.AlterModelTable(
            name='anticheatconfigurations',
            table='anticheat_configurations',
        ),
        migrations.CreateModel(
            name='AntiCheatConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(max_length=64)),
                ('tip', models.TextField(blank=True, null=True)),
                ('pseudo_name', models.CharField(max_length=32, unique=True)),
                ('server_type', models.IntegerField(choices=[(2, 'FiveM')], default=2)),
                ('config_type', models.IntegerField(choices=[(1, 'Boolean'), (2, 'String'), (3, 'Integer')], default=1)),
                ('default_value', models.CharField(blank=True, max_length=512)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='anticheat.anticheatconfigsection')),
            ],
            options={
                'verbose_name': 'Configuration Template',
                'verbose_name_plural': 'Configuration Templates',
            },
        ),
        migrations.AddField(
            model_name='anticheatconfigsection',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='anticheat.anticheatconfigurationcategory'),
        ),
        migrations.DeleteModel(
            name='AntiCheatConfigTemplates',
        ),
        migrations.DeleteModel(
            name='AntiCheatConfigurationCategories',
        ),
    ]
