# Generated by Django 5.2.5 on 2025-08-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0055_anticheatconfigsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticheatconfigurationcategory',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
