# Generated by Django 5.2.5 on 2025-08-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0056_anticheatconfigurationcategory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticheatconfigtemplate',
            name='config_type',
            field=models.IntegerField(choices=[('boolean', 'Boolean'), ('string', 'String'), ('number', 'Number'), ('select', 'Select'), ('file_upload', 'File Upload'), ('file_export', 'File Export'), ('embed_json', 'Embed Json')], default='boolean'),
        ),
    ]
