# Generated by Django 5.2.5 on 2025-08-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0059_falsepositivereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticheatconfigsection',
            name='tooltip',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anticheatconfigtemplate',
            name='config_type',
            field=models.TextField(choices=[('boolean', 'Boolean'), ('string', 'String'), ('number', 'Number'), ('select', 'Select'), ('file_upload', 'File Upload'), ('export_json', 'File Export'), ('embed_json', 'Embed Json')], default='boolean'),
        ),
        migrations.AlterField(
            model_name='falsepositivereport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved (False Positive)'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
