# Generated by Django 5.2.5 on 2025-08-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0060_anticheatconfigsection_tooltip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticheatconfigsection',
            name='tooltip',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
