# Generated by Django 5.2.5 on 2025-08-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0061_alter_anticheatconfigsection_tooltip'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticheatconfigtemplate',
            name='extra',
            field=models.JSONField(default=dict),
        ),
    ]
