# Generated by Django 5.2.5 on 2025-08-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0062_anticheatconfigtemplate_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticheatconfigurations',
            name='server_image',
            field=models.ImageField(null=True, upload_to='server_images'),
        ),
    ]
