# Generated by Django 5.2.5 on 2025-08-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0063_anticheatconfigurations_server_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticheatconfigurations',
            name='server_image',
            field=models.ImageField(null=True, upload_to='servers_images'),
        ),
    ]
