# Generated by Django 5.2.5 on 2025-08-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0064_alter_anticheatconfigurations_server_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticheatconfigtemplate',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
