# Generated by Django 5.2.5 on 2025-08-15 22:44

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0065_alter_anticheatconfigtemplate_extra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalHWID',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('computer_name', models.CharField(max_length=64)),
                ('disks', models.JSONField(default=list)),
                ('cpuid', models.CharField(max_length=64)),
                ('motherboard_serial', models.CharField(max_length=64)),
                ('bios_version', models.CharField(max_length=32)),
                ('pnp_device', models.CharField(max_length=512)),
                ('fivem_license', models.CharField(max_length=64, null=True)),
                ('fivem_token', models.JSONField(blank=True, default=list)),
                ('steam', models.CharField(max_length=64, null=True)),
                ('discord_id', models.CharField(max_length=64, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical HWID',
                'verbose_name_plural': 'historical HWIDs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
