# Generated by Django 5.2.5 on 2025-08-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0066_historicalhwid'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticheatconfigurations',
            name='webhooks',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='hwids_logs',
        ),
    ]
