# Generated by Django 5.2.5 on 2025-08-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0067_anticheatconfigurations_webhooks_delete_hwids_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticheatconfigurations',
            name='embeds',
            field=models.JSONField(default=dict),
        ),
    ]
