# Generated by Django 5.2.5 on 2025-08-19 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0068_anticheatconfigurations_embeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falsepositivereport',
            name='ban',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='false_positive_report', to='anticheat.ban'),
        ),
    ]
