# Generated by Django 5.2.5 on 2025-08-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0069_alter_falsepositivereport_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionreport',
            name='detection_type',
            field=models.IntegerField(choices=[(0, 'Custom'), (1, 'Unauthorized Thread'), (2, 'Unrecognized IAT'), (3, 'Direct X DLL Found'), (4, 'Secure Boot Disabled'), (5, 'Debug Mode Enabled'), (6, 'Test Signing Enabled'), (7, 'Injected DLL'), (8, 'Cheat Signature Found'), (9, 'Malicious Process opened FiveM handle'), (10, 'Malicious Driver Found'), (11, 'Thread Shell Code'), (12, 'Memory Integrity Disabled')]),
        ),
    ]
