# Generated by Django 5.2.5 on 2025-08-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0070_alter_detectionreport_detection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatfile',
            name='hash',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
