# Generated by Django 5.2.5 on 2025-09-14 11:19

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0071_alter_threatfile_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhwid',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 9, 14, 11, 19, 2, 258542, tzinfo=datetime.timezone.utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalhwid',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 9, 14, 11, 19, 8, 212056, tzinfo=datetime.timezone.utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hwid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hwid',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
