# Generated by Django 5.2.5 on 2025-10-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0072_historicalhwid_created_at_historicalhwid_last_seen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtomicEngineReleaseAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('file', models.FileField(upload_to='engines/')),
                ('note', models.TextField()),
                ('version', models.CharField(max_length=16, null=True)),
                ('release_type', models.IntegerField(choices=[(1, 'Debug'), (2, 'Release')])),
                ('current_engine', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
