# Generated by Django 5.2.5 on 2025-10-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0073_atomicenginereleaseasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomicenginereleaseasset',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
