# Generated by Django 5.2.5 on 2025-10-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0074_alter_atomicenginereleaseasset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomicenginereleaseasset',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atomicenginereleaseasset',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
