# Generated by Django 5.0.7 on 2024-09-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0003_alter_ban_ends_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ban',
            old_name='ends_at',
            new_name='duration',
        ),
    ]
