# Generated by Django 5.0.7 on 2024-10-02 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0004_rename_ends_at_ban_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='malicioussignatures',
            name='ban_duaration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=3600)),
            preserve_default=False,
        ),
    ]
