# Generated by Django 5.0.7 on 2024-10-30 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0013_ban_active'),
        ('dashboard', '0007_alter_announcements_options_alter_gameserver_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='game_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.gameserver'),
        ),
    ]
