# Generated by Django 5.0.7 on 2024-11-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0016_clienthwid_pnp_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienthwid',
            name='pnp_device',
            field=models.CharField(max_length=512),
        ),
    ]
