# Generated by Django 5.0.7 on 2024-11-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0017_alter_clienthwid_pnp_device'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clienthwid',
            table='hwids',
        ),
    ]
