# Generated by Django 5.0.7 on 2025-01-05 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticheat', '0019_alter_anticheatconfigtemplates_server_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectionreport',
            options={'verbose_name': 'Detection Report', 'verbose_name_plural': 'Detection Reports'},
        ),
        migrations.AddField(
            model_name='ban',
            name='report',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='anticheat.detectionreport'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='detectionreport',
            table='detection_reports',
        ),
    ]
